// <auto-generated />
using System;
using BookItsUp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace BookItsUp.DataAccess.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20251014224446_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("CustomerId1")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id1");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc");

                    b.Property<DateTimeOffset?>("HoldExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at_utc");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<Guid>("ProviderId1")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id1");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("ServiceId1")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id1");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<NpgsqlRange<DateTimeOffset>>("slot")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tstzrange")
                        .HasColumnName("slot")
                        .HasComputedColumnSql("tstzrange(start_utc, end_utc, '[)')", true);

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CustomerId1")
                        .HasDatabaseName("ix_bookings_customer_id1");

                    b.HasIndex("ProviderId1")
                        .HasDatabaseName("ix_bookings_provider_id1");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_bookings_service_id");

                    b.HasIndex("ServiceId1")
                        .HasDatabaseName("ix_bookings_service_id1");

                    b.HasIndex("CustomerId", "StartUtc")
                        .HasDatabaseName("ix_bookings_customer_id_start_utc");

                    b.HasIndex("ProviderId", "StartUtc")
                        .HasDatabaseName("ix_bookings_provider_id_start_utc");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("OrganizationId", "Email")
                        .HasDatabaseName("ix_customers_organization_id_email");

                    b.HasIndex("OrganizationId", "Phone")
                        .HasDatabaseName("ix_customers_organization_id_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.DailySegmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndLocalTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_local_time");

                    b.Property<TimeSpan>("StartLocalTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_local_time");

                    b.Property<Guid>("WeeklyScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("weekly_schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_daily_segments");

                    b.HasIndex("WeeklyScheduleId", "DayOfWeek", "StartLocalTime", "EndLocalTime")
                        .IsUnique()
                        .HasDatabaseName("ix_daily_segments_weekly_schedule_id_day_of_week_start_local_t");

                    b.ToTable("daily_segments", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.LocalTimeRangeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("EndLocalTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_local_time");

                    b.Property<Guid>("ScheduleExceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_exception_id");

                    b.Property<TimeSpan>("StartLocalTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_local_time");

                    b.HasKey("Id")
                        .HasName("pk_local_time_ranges");

                    b.HasIndex("ScheduleExceptionId", "StartLocalTime", "EndLocalTime")
                        .IsUnique()
                        .HasDatabaseName("ix_local_time_ranges_schedule_exception_id_start_local_time_en");

                    b.ToTable("local_time_ranges", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.ProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_providers_organization_id_name");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.ScheduleExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_schedule_exceptions");

                    b.HasIndex("ProviderId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_exceptions_provider_id_date");

                    b.ToTable("schedule_exceptions", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BufferAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("buffer_after_minutes");

                    b.Property<int>("BufferBeforeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("buffer_before_minutes");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_services_organization_id_name");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.WeeklyScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("pk_weekly_schedules");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_schedules_provider_id");

                    b.ToTable("weekly_schedules", (string)null);
                });

            modelBuilder.Entity("BookItsUp.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("BookItsUp.Domain.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("pk_provider");

                    b.ToTable("provider", (string)null);
                });

            modelBuilder.Entity("BookItsUp.Domain.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BufferAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("buffer_after_minutes");

                    b.Property<int>("BufferBeforeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("buffer_before_minutes");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("price_cents");

                    b.HasKey("Id")
                        .HasName("pk_service");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.BookingEntity", b =>
                {
                    b.HasOne("BookItsUp.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customer_customer_id");

                    b.HasOne("BookItsUp.DataAccess.Entities.CustomerEntity", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_customers_customer_id1");

                    b.HasOne("BookItsUp.Domain.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_provider_provider_id");

                    b.HasOne("BookItsUp.DataAccess.Entities.ProviderEntity", "Provider")
                        .WithMany("Bookings")
                        .HasForeignKey("ProviderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_providers_provider_id1");

                    b.HasOne("BookItsUp.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_service_service_id");

                    b.HasOne("BookItsUp.DataAccess.Entities.ServiceEntity", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_services_service_id1");

                    b.Navigation("Customer");

                    b.Navigation("Provider");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.DailySegmentEntity", b =>
                {
                    b.HasOne("BookItsUp.DataAccess.Entities.WeeklyScheduleEntity", "WeeklySchedule")
                        .WithMany("Segments")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_daily_segments_weekly_schedules_weekly_schedule_id");

                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.LocalTimeRangeEntity", b =>
                {
                    b.HasOne("BookItsUp.DataAccess.Entities.ScheduleExceptionEntity", "ScheduleException")
                        .WithMany("LocalTimeRanges")
                        .HasForeignKey("ScheduleExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_local_time_ranges_schedule_exceptions_schedule_exception_id");

                    b.Navigation("ScheduleException");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.ScheduleExceptionEntity", b =>
                {
                    b.HasOne("BookItsUp.DataAccess.Entities.ProviderEntity", "Provider")
                        .WithMany("ScheduleExceptions")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_exceptions_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.WeeklyScheduleEntity", b =>
                {
                    b.HasOne("BookItsUp.DataAccess.Entities.ProviderEntity", "Provider")
                        .WithOne("WeeklySchedule")
                        .HasForeignKey("BookItsUp.DataAccess.Entities.WeeklyScheduleEntity", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weekly_schedules_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.ProviderEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ScheduleExceptions");

                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.ScheduleExceptionEntity", b =>
                {
                    b.Navigation("LocalTimeRanges");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.ServiceEntity", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BookItsUp.DataAccess.Entities.WeeklyScheduleEntity", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
